[package]
name = "apriltag-rs"
version = "0.1.0"
edition = "2021"

[lib]
# crate-type = ["cdylib"]

[features]
cpython = ["dep:cpython"]
jni = ["dep:jni"]
cffi = ["dep:libc", "dep:nix", "dep:errno"]
debug = []
extra_debug = ["debug"]
compare_reference = ["apriltag-sys/deep", "dep:float-cmp", "dep:libc"]

default = ["cpython", "jni", "debug", "cffi", "dep:opencv"]
# default = ["debug"]
# default = ["debug", "compare_reference", "extra_debug"]

[profile.dev]
default = ["cpython", "jni", "cffi", "debug", "extra_debug"]

[profile.release]
default = ["cpython", "jni", "cffi"]


[dependencies]
arrayvec = "0.7.2"
rand = "0.8.5"
rayon = "1.6.1"
datasize = "0.2.14"
clap = { version = "4.2.1", features=["derive"] }
parking_lot = "0.12.1"
raw-parts = "2.0.0"

# Feature: Python FFI
[dependencies.cpython]
version = "0.7.1"
optional = true
features=["extension-module"]
# Feature: Java FFI
[dependencies.jni]
version = "0.21.1"
optional = true

# Feature: C FFI
[dependencies.libc]
version = "0.2.139"
optional = true
[dependencies.nix]
version = "0.26.2"
optional = true
[dependencies.errno]
version = "0.3.1"
optional = true

[dependencies.apriltag-sys]
path="../apriltag-rust-deep/apriltag-sys"
optional = true
[dependencies.float-cmp]
version = "0.9.0"
optional = true


[dev-dependencies]
image = "0.24.6"

[dependencies.opencv]
version = "0.83.0"
features = ["clang-runtime"]
optional = true